name: React Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t victor823543/ranking-room-frontend --build-arg API_ADDRESS="${{ secrets.API_ADDRESS }}" --build-arg GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" .
      - name: Publish Image to Docker Hub
        run: docker push victor823543/ranking-room-frontend:latest

  deploy:
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull victor823543/ranking-room-frontend:latest
      - name: Delete old container
        run: docker rm -f react-app-container
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name react-app-container victor823543/ranking-room-frontend
